### ISSUE TITLE
Unable to accept license for Android Build-Tools 28.0.3

### ISSUE THREAD

**Issue by darlancandiotto18** [bitrise-steplib/steps-install-missing-android-tools#62] opened 2020-07-20 20:42 UTC
I'm trying to compile my application using bitrise but the following exception occurs:

```
> Configure project :@react-native-community_async-storage
Checking the license for package Android SDK Build-Tools 28.0.3 in /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@react-native-community_async-storage'.

> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':@react-native-community_async-storage'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:72)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$600(LifecycleProjectEvaluator.java:53)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:198)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject$1.run(LifecycleProjectEvaluator.java:111)
	at org.gradle.internal.Factories$1.create(Factories.java:25)
```

**Comment by shockdesign** [comment] 2020-07-20 23:01
Just jumping in to say I'm having the same issue.

Using the `Visual Studio for Mac, Stable channel` stack.

**Comment by non-binary** [comment] 2020-07-21 11:19
@shockdesign @darlancandiotto18 Can either of you send a link to a build and enable support access please?

**Comment by shockdesign** [comment] 2020-07-21 15:35
@non-binary I've enabled support access and here is a link - https://app.bitrise.io/build/b3e11d5475e3e196#?tab=log

**Comment by chaitanyatanna-bitrise** [comment] 2020-07-29 17:07
Hi @shockdesign 
Thank you for enabling the build URL for us. 
Can you please make sure that you install the correct SDK version for Android to be run on?

Thank you
Chaitanya

**Comment by shockdesign** [comment] 2020-08-04 13:47
Okay, fixed this by just making sure I accept the license before the build starts...

```
yes | sdkmanager --licenses
```

**Comment by chaitanyatanna-bitrise** [comment] 2020-08-04 14:07
Hi @shockdesign 
Thank you for the update. I am glad that the issue got fixed.

Thank you
Chaitanya

**Comment by shockdesign** [comment] 2021-04-02 12:18
@darlancandiotto18 Did accepting the licence as above help you?

**Comment by mefiblogger** [comment] 2021-04-15 10:13
Hello,

It's Mefi here from the Bitrise CoreSteps Team. Thanks for reaching out helping us and the mobile community to have a better experience with Bitrise steps. 💜

We started to have a broader review of all the open issues and PRs and we are continuously prioritizing these in our sprints.

We reviewed this issue and we found it to be a valid bug. We added this ticket to our internal backlog and we'll get back to you once we released the new version of this step.

Happy building! 🚀

**Comment by mateherber** [comment] 2021-04-23 10:09
Hi!

I've investigated this issue and found several things to consider. In my test our `Visual Studio for Mac, Stable channel` stack could run this step properly for an Android project and install its dependencies well. In the build-log that @shockdesign shared the tools are not installed via this step but a lane in fastlane. In that case unfortunately there is no better option than the already referenced `yes | sdkmanager --licenses` or using this step (which more or less does the same). 

In the original report it seems also a build step tried to install tools for the SDK and not this step. I can't check the log as it was not shared. I assume the workaround found above could help in that case.

I'm closing this issue now as I think the step is working as intended, at least I couldn't reproduce failure on our VS stack using this step.

**Closed by mateherber** 2021-04-23 10:09 UTC
Labels: bug
