### ISSUE TITLE
version 2.3.8 failing across all builds

### ISSUE THREAD

**Issue by prfarlow1** [bitrise-steplib/steps-install-missing-android-tools#66] opened 2020-12-10 22:03 UTC
When the step gets to "Ensure required Android SDK components", it's failing 
```
Ensure required Android SDK components
Retrying...
Failed to ensure android components, error: output: FAILURE: Build failed with an exception.
* What went wrong:
Could not load compiled classes for settings file '/[REDACTED]/src/settings.gradle' from cache. Expected class file /root/.gradle/caches/jars-8/c09e2a1b661a58f8283b8fe94748d8fd/settings.jar/settings_2fggozq45hw451w290ssabnr7.class does not exist.
> settings_2fggozq45hw451w290ssabnr7
org.gradle.api.GradleException: Could not load compiled classes for settings file '/[REDACTED]/src/settings.gradle' from cache. Expected class file /root/.gradle/caches/jars-8/c09e2a1b661a58f8283b8fe94748d8fd/settings.jar/settings_2fggozq45hw451w290ssabnr7.class does not exist.

```

**Comment by Tooto** [comment] 2020-12-11 10:53
Same problem.
Drop caches on Settings tab will help you
![image](https://user-images.githubusercontent.com/3471723/101894429-35a51f80-3bb7-11eb-998f-cae7300d1038.png)

**Comment by mateherber** [comment] 2021-01-07 09:08
This was caused by a bug in the cache-push step corrupting the gradle cache. Please delete the cache manually and it "solves" this issue. I'm closing this now.

**Closed by mateherber** 2021-01-07 09:08 UTC
