### ISSUE TITLE
Failed to ensure android components, error: output:

### ISSUE THREAD

**Issue by timrijckaert** [bitrise-steplib/steps-install-missing-android-tools#60] opened 2020-02-07 22:56 UTC
I got the following error:
> Failed to ensure android components, error: output:

Stacks:
- Android & Docker, on Ubuntu 16.04 - LTS Stack
- Android & Docker, on Ubuntu 16.04

```
+------------------------------------------------------------------------------+

| (2) install-missing-android-tools@2.3.8                                      |
+------------------------------------------------------------------------------+
| id: install-missing-android-tools                                            |
| version: 2.3.8                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-02-07T22:30:32Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[22:30:32] Start installing (golang) with apt-get       
INFO[22:30:32]  * [OK] Step dependency (go) installed, available. 
Configs:
- GradlewPath: android/gradlew
- AndroidHome: /opt/android-sdk-linux
- NDKRevision: 
Preparation
Set executable permission for gradlew
Clearing NDK environment
Unset ANDROID_NDK_HOME
Initialize Android SDK
Ensure android licences
Ensure required Android SDK components
Retrying...
Failed to ensure android components, error: output: > Task :buildSrc:compileKotlin UP-TO-DATE
```

**Comment by timrijckaert** [comment] 2020-02-08 10:12
https://github.com/bitrise-io/android/pull/279

Might be related

**Comment by tokou** [comment] 2020-10-06 14:43
Any updates or workaround on this?
The linked issue has been merged upstream it seems.

**Comment by bpappin** [comment] 2021-03-16 19:41
Aht command is it actually running? it maddening that bitrise hides all the details from us.

**Comment by mjones-droid** [comment] 2021-04-12 14:52
Hey everyone! I just want to check in to see if this is actually still happening. We've released several image updates which may have resolved this. 

It looks like this failure happens when the steps sdkmanager attempts to ensure the Android SDK is installed properly.

**Comment by marcoRS** [comment] 2021-05-06 15:24
This is now happening to me only after upgrading to AGP 4.2.0 and Kotlin 1.5.0 , though I think it may just be due to AGP 4.2.0 update

**Comment by marcoRS** [comment] 2021-05-06 18:18
Actually this seems to be happening for us when updating to Kotlin 1.5.0 on an Android project. The lint checker is failing incorrectly with the following error: 

Were using the following extension function `forEach`: 
```
params?.forEach { (k, v) -> urlBuilder.addQueryParameter(k, v) } 
```
and the error is: 
```
Call requires API level 24 (current min is 23): java.util.Map#forEach
``` 

However this is a Kotlin extension function that has the following definition: 
```
/**
 * Performs the given [action] on each entry.
 */
@kotlin.internal.HidesMembers
public inline fun <K, V> Map<out K, V>.forEach(action: (Map.Entry<K, V>) -> Unit): Unit {
    for (element in this) action(element)
}
```

**Comment by ofalvai** [comment] 2021-05-14 11:28
Hey @marcoRS,
We recently upgraded our [Android sample project](https://github.com/bitrise-io/Bitrise-Android-Sample) to AGP 4.2.0 and Kotlin 1.5.0. After the upgrade, the build was green on Bitrise: https://app.bitrise.io/build/84d883bf8d35ecd4#?tab=log

I wouldn't rule out a bug in Bitrise completely, but I would look elsewhere first. Checking the [release notes of AGP 4.2.0](https://developer.android.com/studio/releases/gradle-plugin#java-8-default), I see that the default JVM language level has changed to Java 8. If your project doesn't have an explicit language level defined in build.gradle, then maybe this is the change that breaks the builds.

**Comment by marcoRS** [comment] 2021-05-14 13:39
@ofalvai Does your project use `forEach` like the examples I linked to. The linter seems to be failing our build for this type of usage: 
`params?.forEach { (k, v) -> urlBuilder.addQueryParameter(k, v) } `

**Comment by Roland-Bak** [comment] 2021-05-25 09:05
Hey there,

In case anyone else finds their way to this post, I wanted to let you know that the Kotlin related issue happens locally as well, so it is not necessarily Bitrise related 🙂

**Comment by mateherber** [comment] 2021-08-05 13:36
Hi @marcoRS, 

The failure for the line you referenced is due to a new lint check that was introduced along with AGP 4.2. It fails for lines like 

```
mapOf("foo" to "bar").forEach { key, value -> println("$key -> $value") }
```

Which mistakenly uses java's `default void forEach(BiConsumer<? super K, ? super V> action)` instead of kotlin's `foreach` and [destructuring](https://kotlinlang.org/docs/destructuring-declarations.html):

```
mapOf("foo" to "bar").forEach { (key, value) -> println("$key -> $value") }
```

Java's `Map.foreach` is available only from API level 24 on Android hence they introduced the Lint check for those who target 23 or below. On those devices, the first syntax would cause a runtime crash.

For the report generally, the steps at some paths use Gradle to download the needed tools and it involves configuring the project. Should a project has some misconfiguration or failing checks the step will fail with that error. In those cases, the issue is not in the step itself but the project build files/configuration.

**Closed** 2021-08-05 13:38 UTC
