### ISSUE TITLE
can't install sdk tools for android-29

### ISSUE THREAD

**Issue by fleficher** [bitrise-steplib/steps-install-missing-android-tools#57] opened 2019-08-28 21:45 UTC
Hi,

Using v2.3.7 of this step, with a project with the following project configuration:

- build-tools : 29.0.2
- compile sdk: 29
- target sdk: 29

The step fail everytime with the following message:

```
+------------------------------------------------------------------------------+

| (3) install-missing-android-tools@2.3.7                                      |
+------------------------------------------------------------------------------+
| id: install-missing-android-tools                                            |
| version: 2.3.7                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-08-28T21:35:58Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[21:35:58]  * [OK] Step dependency (go) installed, available. 
Configs:
- GradlewPath: ./gradlew
- AndroidHome: /usr/local/share/android-sdk
- NDKRevision: 
Preparation
Set executable permission for gradlew
Clearing NDK environment
Unset ANDROID_NDK_HOME
Initialize Android SDK
Ensure android licences
Ensure required Android SDK components
Retrying...
Failed to ensure android components, error: output: > Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validateTaskProperties UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Configure project :app
Checking the license for package Android SDK Build-Tools 29.0.2 in /usr/local/share/android-sdk/licenses
License for package Android SDK Build-Tools 29.0.2 accepted.
Preparing "Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)".
Warning: Failed to read or create install properties file.
Checking the license for package Android SDK Platform 29 in /usr/local/share/android-sdk/licenses
License for package Android SDK Platform 29 accepted.
Preparing "Install Android SDK Platform 29 (revision: 3)".
Warning: Failed to read or create install properties file.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':data:api'.
> Failed to install the following SDK components:
      build-tools;29.0.2 Android SDK Build-Tools 29.0.2
      platforms;android-29 Android SDK Platform 29
  Install the missing components using the SDK manager in Android Studio.


```

**Comment by fleficher** [comment] 2019-08-29 06:58
By the way, this issue is occurring using any macOS stack. There is no issue on Android + Ubuntu stack because it's already installed on them but they are too slow to be used?

**Comment by bitce** [comment] 2019-08-29 14:55
Hi @fleficher! 

Could you send us the corresponding build URL we could check out?

**Comment by fleficher** [comment] 2019-08-30 07:21
Hi @bitce sure, you can check this one: https://app.bitrise.io/build/21141196c3ec21c7

**Comment by brittonjg** [comment] 2019-09-03 12:11
It's because the Mac stacks don't include android-29. I have tried using the Ubuntu stacks, but that causes other issues with our setup 😕

**Comment by brittonjg** [comment] 2019-09-03 12:37
![Screenshot 2019-09-03 at 13 33 25](https://user-images.githubusercontent.com/12110204/64173570-81fb9e80-ce4f-11e9-922f-082dc11424ad.png)

My workflow is getting passed my _install-missing-android-tools, saying that the Android version is installed.

It then fails when the gradle tasks executes, with a similar warning to what @fleficher has posted. I am running this on a Mac Stack, I've tried switching to the Ubuntu Stack which has android-29 installed. Although I get other issues with that, which are related to our setup.

**Comment by JeromeCHA** [comment] 2019-09-04 04:00
We have the same issue too. 
It is impossible to install missing SDK android-29 on Mac Stack. It fails with the same error
```
Checking the license for package Android SDK Build-Tools 29 in /usr/local/share/[REDACTED]-sdk/licenses
License for package Android SDK Build-Tools 29 accepted.
Preparing "Install Android SDK Build-Tools 29 (revision: 29.0.0)".
Warning: Failed to read or create install properties file.
Checking the license for package Android SDK Platform 29 in /usr/local/share/[REDACTED]-sdk/licenses
License for package Android SDK Platform 29 accepted.
Preparing "Install Android SDK Platform 29 (revision: 3)".
Warning: Failed to read or create install properties file.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following SDK components:
      build-tools;29.0.0 Android SDK Build-Tools 29
      platforms;[REDACTED]-29 Android SDK Platform 29
  Install the missing components using the SDK manager in Android Studio.
```

**Comment by bitce** [comment] 2019-09-05 05:57
Thanks for all the reports guys and sorry about this issue! We're looking at it and will keep you all updated.

**Comment by fleficher** [comment] 2019-09-20 15:46
Hit @bitce do you have any news on this issue ?

**Comment by koral--** [comment] 2019-09-20 15:52
Workaround is to invoke `sudo chmod -R a+w /usr/local/Caskroom/android-sdk` in a script step.

**Comment by lszucs** [comment] 2019-10-04 13:52
Hi @fleficher , @brittonjg 

Can you confirm whether the issue still persist? I cannot reproduce it on either an XCode 10 or an Xcode 11 stack.

If the issue persists, can you please reach out on the chat and reference this thread to fast forward it to level 3 support? (The Tooling Team :) )

**Comment by brittonjg** [comment] 2019-10-04 14:19
> Hi @fleficher , @brittonjg
> 
> Can you confirm whether the issue still persist? I cannot reproduce it on either an XCode 10 or an Xcode 11 stack.
> 
> If the issue persists, can you please reach out on the chat and reference this thread to fast forward it to level 3 support? (The Tooling Team :) )

This appears to be resolved for us now.

If makes any difference, I am using a React setup with the XCode 10.1 stack. Although as mentioned above, it's not causing us an issue anymore.

**Comment by lszucs** [comment] 2019-10-14 12:46
Hi @fleficher 

I'll close this issue for now, as it seems the problem has been solved. Do not hesitate to reopen it, if your issue persist! :)

Thanks for the report!

**Comment by Luk164** [comment] 2020-02-06 17:02
This issue has resurfaced with the new 29.0.3 version.

**Comment by timrijckaert** [comment] 2020-02-07 22:52
Same here.  
Latest version of the step `2.3.8`

Stack
- Android & Docker, on Ubuntu 16.04 - LTS Stack
- Android & Docker, on Ubuntu 16.04

```
...
Clearing NDK environment
Unset ANDROID_NDK_HOME
Initialize Android SDK
Ensure android licences
Ensure required Android SDK components
Retrying...
Failed to ensure android components, error: output: > Task :buildSrc:compileKotlin UP-TO-DATE
...
```

**Comment by non-binary** [comment] 2020-02-20 21:49
Hi @Luk164 @timrijckaert,

Thank you for reaching out.

Can you please share a new build log that reproduces this behaviour?

Thanks,
Luna

**Comment by Luk164** [comment] 2020-02-21 11:23
[logs_10.zip](https://github.com/bitrise-steplib/steps-install-missing-android-tools/files/4235764/logs_10.zip)

**Comment by Luk164** [comment] 2020-03-04 22:49
> Hi @Luk164 @timrijckaert,
> 
> Thank you for reaching out.
> 
> Can you please share a new build log that reproduces this behaviour?
> 
> Thanks,
> Luna

The issue has still not been resolved, can you give is any progress?

**Comment by soodkartik24** [comment] 2020-03-07 21:20
Failed to install the following Android SDK packages as some licences have not been accepted.
      build-tools;29.0.3 Android SDK Build-Tools 29.0.3
      platforms;android-29 Android SDK Platform 29

**Comment by non-binary** [comment] 2020-03-17 13:59
This has been escalated to L3. Thank you for your patience as they look into this.

**Comment by non-binary** [comment] 2020-03-25 13:17
Thank you for your patience. L3 has determined this is an infrastructure issue so I have escalated this to our infra team. I will follow-up as soon as I get an update from them.

**Comment by non-binary** [comment] 2020-03-25 13:17
(Oops didn't mean to close it.)

**Comment by Luk164** [comment] 2020-03-25 13:20
@non-binary  Oh come on you made me think it was fixed finally. BTW using sude seems to be a pretty good workaround

**Comment by non-binary** [comment] 2020-03-25 13:24
Great news! Actually a fix was merged in yesterday and so this issue should be fixed. 🎉Please don't hesitate to follow-up if this is not the case or if you have any other questions.

**Comment by non-binary** [comment] 2020-03-25 13:24
@Luk164 Fortunately just heard back and it actually is fixed. Sorry for the confusion!

**Closed by non-binary** 2020-03-25 13:24 UTC

**Comment by ahmedeltaher** [comment] 2020-06-25 20:39
Still, the same issue!
<img width="1433" alt="Screenshot 2020-06-25 at 22 38 57" src="https://user-images.githubusercontent.com/1812129/85793037-b325c200-b734-11ea-92ac-7203d58bd335.png">

**Comment by nadernmds** [comment] 2021-01-23 16:30
> Workaround is to invoke `sudo chmod -R a+w /usr/local/Caskroom/android-sdk` in a script step.

This solved my problem 
thanks man
